export const API_KEY = '1990333215773402'
export const ADDRESS_URL = 'https://us-street.api.smartystreets.com/street-address?auth-id='
export const ADDRESS_URL_PT2 = '&candidates=10&street='
export const ADDRESS_URL_PT3 = '&city=&state-&zipcode-'
export const ZIPCODE_URL = 'https://us-zipcode.api.smartystreets.com/lookup?auth-id='
export const ZIPCODE_URL_PT2 = '&city=&state-&zipcode='